package com.keba.kemro.teach.network.rpc.protocol;

import com.keba.jrpc.rpc.*;
import java.io.*;

public class RpcTcSymbolKind implements XDR {
	public static final int rpcTComment = -2;
	public static final int rpcTError = -1;
	public static final int rpcTEof = 0;
	public static final int rpcTInherit = 1;
	public static final int rpcTSemicolon = 2;
	public static final int rpcTPrivate = 3;
	public static final int rpcTGlobal = 4;
	public static final int rpcTConst = 5;
	public static final int rpcTValueParam = 6;
	public static final int rpcTSave = 7;
	public static final int rpcTEndSave = 8;
	public static final int rpcTColonEqual = 9;
	public static final int rpcTConstant = 10;
	public static final int rpcTEndConstant = 11;
	public static final int rpcTColon = 12;
	public static final int rpcTVar = 13;
	public static final int rpcTEndVar = 14;
	public static final int rpcTType = 15;
	public static final int rpcTEndType = 16;
	public static final int rpcTMapTo = 17;
	public static final int rpcTRoutine = 18;
	public static final int rpcTParenthesesLeft = 19;
	public static final int rpcTParenthesesRight = 20;
	public static final int rpcTBracketLeft = 21;
	public static final int rpcTBracketRight = 22;
	public static final int rpcTDoublePoint = 23;
	public static final int rpcTComma = 24;
	public static final int rpcTArray = 25;
	public static final int rpcTOf = 26;
	public static final int rpcTStruct = 27;
	public static final int rpcTEndStruct = 28;
	public static final int rpcTCase = 29;
	public static final int rpcTEndRoutine = 30;
	public static final int rpcTAt = 31;
	public static final int rpcTStart = 32;
	public static final int rpcTPrio = 33;
	public static final int rpcTDo = 34;
	public static final int rpcTStop = 35;
	public static final int rpcTIf = 36;
	public static final int rpcTThen = 37;
	public static final int rpcTEndIf = 38;
	public static final int rpcTElseIf = 39;
	public static final int rpcTElse = 40;
	public static final int rpcTGoto = 41;
	public static final int rpcTEndCase = 42;
	public static final int rpcTFor = 43;
	public static final int rpcTTo = 44;
	public static final int rpcTEndFor = 45;
	public static final int rpcTWhile = 46;
	public static final int rpcTEndWhile = 47;
	public static final int rpcTRepeat = 48;
	public static final int rpcTUntil = 49;
	public static final int rpcTEndRepeat = 50;
	public static final int rpcTLabel = 51;
	public static final int rpcTSelect = 52;
	public static final int rpcTDeselect = 53;
	public static final int rpcTReturn = 54;
	public static final int rpcTWait = 55;
	public static final int rpcTPoint = 56;
	public static final int rpcTLess = 57;
	public static final int rpcTGreater = 58;
	public static final int rpcTLessEqual = 59;
	public static final int rpcTGreaterEqual = 60;
	public static final int rpcTEqual = 61;
	public static final int rpcTNotEqual = 62;
	public static final int rpcTMinus = 63;
	public static final int rpcTPlus = 64;
	public static final int rpcTOr = 65;
	public static final int rpcTXor = 66;
	public static final int rpcTMul = 67;
	public static final int rpcTDiv = 68;
	public static final int rpcTMod = 69;
	public static final int rpcTAnd = 70;
	public static final int rpcTNot = 71;
	public static final int rpcTIdent = 72;
	public static final int rpcTInteger = 73;
	public static final int rpcTReal = 74;
	public static final int rpcTString = 75;
	public static final int rpcTLock = 76;
	public static final int rpcTUnlock = 77;
	public static final int rpcTNewLine = 78;
	public static final int rpcTUser = 79;
	public static final int rpcTLoop = 80;
	public static final int rpcTEndLoop = 81;
	public static final int rpcTCall = 82;
	public static final int rpcTOptional = 83;
	public static final int rpcTProject = 84;
	public static final int rpcTCurlyBracketLeft = 85;
	public static final int rpcTCurlyBracketRight = 86;
	public static final int rpcTAttrSeperator = 87;
	public static final int rpcTName = 88;
	public static final int rpcTReadonly = 89;
	public static final int rpcTRun = 90;
	public static final int rpcTKill = 91;
	public static final int rpcTAbstract = 92;
	public static final int rpcTDeactivate = 93;
	public static final int rpcTBegin = 94;
	public static final int rpcTEnd = 95;
	public static final int rpcTDeprecated = 96;
	public static final int rpcNTConstPart = 101;
	public static final int rpcNTVarPart = 102;
	public static final int rpcNTTypePart = 103;
	public static final int rpcNTVarDeclaration = 104;
	public static final int rpcNTTypeDefinition = 105;
	public static final int rpcNTConstDeclaration = 106;
	public static final int rpcNTStatementPart = 107;
	public static final int rpcNTParameter = 108;
	public static final int rpcNTEnumeration = 109;
	public static final int rpcNTEnumerationType = 110;
	public static final int rpcNTStructType = 111;
	public static final int rpcNTArrayType = 112;
	public static final int rpcNTFunctionBlock = 120;
	public static final int rpcNTAtBlock = 121;
	public static final int rpcNTHead = 122;
	public static final int rpcNTAtHead = 123;
	public static final int rpcNTAttribBlock = 124;
	public static final int rpcNTEmptyStatement = 130;
	public static final int rpcNTAssignStatement = 131;
	public static final int rpcNTCallStatement = 132;
	public static final int rpcNTWaitStatement = 133;
	public static final int rpcNTIfStatement = 134;
	public static final int rpcNTIfGotoStatement = 135;
	public static final int rpcNTCaseStatement = 136;
	public static final int rpcNTForStatement = 137;
	public static final int rpcNTWhileStatement = 138;
	public static final int rpcNTRepeatStatement = 139;
	public static final int rpcNTReturnStatement = 140;
	public static final int rpcNTLabelStatement = 141;
	public static final int rpcNTGotoStatement = 142;
	public static final int rpcNTSelectStatement = 144;
	public static final int rpcNTDeselectStatement = 145;
	public static final int rpcNTStopStatement = 146;
	public static final int rpcNTLockStatement = 147;
	public static final int rpcNTUnlockStatement = 148;
	public static final int rpcNTLoopStatement = 149;
	public static final int rpcNTCaseSel = 158;
	public static final int rpcNTRoutine = 159;
	public static final int rpcNTExpression = 160;
	public int value;



	public RpcTcSymbolKind () {
	}
	public void write (RPCOutputStream out) throws RPCException, IOException {
		out.writeInt(value); 
	}
	public void read (RPCInputStream in) throws RPCException, IOException {
		value = in.readInt(); 
	}
}